### ISSUE TITLE
Print instead of return

### ISSUE THREAD

**Issue by NoahCristino** [NoahCristino/robloxlib#6]
I am going to fix this but @dogesum you need to make sure that you are returning the value instead of printing it. Like in this: 
`r = requests.get("https://web.roblox.com/UserCheck/GetRecommendedUsername?usernameToTry="+str(username))`
`a = r.text`
`print a`
you should do `return a` instead of printing it so people can get the value rather than printing it out

**Comment by dogesum** [comment]
Sorry about that, I always forget. I will note that and make sure.

**Comment by NoahCristino** [comment]
Ok i'll close the issue :)
