### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by NoahCristino** [NoahCristino/robloxlib#7]
@dogesum Is there anyway I can contact you because there is no message function in github :(

**Comment by dogesum** [comment]
Do you have discord, or even a ROBLOX account?

**Comment by NoahCristino** [comment]
@dogesum both. roblox: cristinon and I'm making a discord channel right now

**Comment by NoahCristino** [comment]
Here's the link: https://discord.gg/myYspr5

**Comment by NoahCristino** [comment]
@dogesum

**Comment by dogesum** [comment]
Ok. When I am able to I will join the discord. I decided ROBLOX would be too hard to communicate with.
