### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by sbhadr** [NoahCristino/robloxlib#9]
Hello and Greetings, 

I am a fellow developer who happens to be working on the same project as I see here.
More info can be found [here](https://github.com/Sanjay-B/Pyblox). Furthermore, I am creating
a server on Discord to help people find the APIs related to Roblox. When I was creating mine, 
I noticed that the general public lacked completed, stable APIs and documentation for Roblox.
Though the server is new and just created, I would love if you could join to help organize the
searching of user-made Roblox APIs.

Thanks, Sanjay

**Comment by NoahCristino** [comment]
Sure what's the discord?

**Comment by sbhadr** [comment]
https://discordapp.com/invite/EDXNdAT
